frontend/modules/repayment/models/EmployerPenalty.php
<?php

namespace frontend\modules\repayment\models;

use Yii;

/**
 * This is the model class for table "employer_penalty".
 *
 * @property integer $employer_penalty_id
 * @property integer $employer_id
 * @property string $amount
 * @property string $penalty_date
 * @property string $created_at
 *
 * @property EmployerPenalty $employer
 * @property EmployerPenalty[] $employerPenalties
 */
class EmployerPenalty extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employer_penalty';
    }
    public $employerName;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //[['employer_id', 'amount', 'penalty_date', 'created_at'], 'required'],
			[['cancel_reason'], 'required','on'=>'Cancell_employer_penalty2'],
            [['employer_id'], 'integer'],
            [['amount'], 'number'],
            [['penalty_date', 'created_at','is_active','canceled_by','canceled_at','cancel_reason','amount','is_active','level','employer_penalty_cycle_id','penalty_id'], 'safe'],
            [['employer_id'], 'exist', 'skipOnError' => true, 'targetClass' => Employer::className(), 'targetAttribute' => ['employer_id' => 'employer_id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'employer_penalty_id' => 'Employer Penalty ID',
            'employer_id' => 'Employer ID',
            'amount' => 'Amount',
            'penalty_date' => 'Penalty Date',
            'created_at' => 'Created At',
			'is_active'=>'is_active',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployer()
    {
        return $this->hasOne(Employer::className(), ['employer_id' => 'employer_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEmployerPenalties()
    {
        return $this->hasMany(EmployerPenalty::className(), ['employer_id' => 'employer_penalty_id']);
    }
public static function getActivePenalty(){	 
	 return self::findBySql("SELECT  *  FROM employer_penalty WHERE  employer_penalty.is_active='1' AND level='1'")->all();
}
}

frontend/modules/repayment/controllers/EmployerPenaltyController.php
<?php

namespace frontend\modules\repayment\controllers;

use Yii;
use frontend\modules\repayment\models\EmployerPenalty;
use frontend\modules\repayment\models\EmployerPenaltySearch;
//use yii\web\Controller;
use \common\components\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use frontend\modules\repayment\models\EmployerSearch;

/**
 * EmployerPenaltyController implements the CRUD actions for EmployerPenalty model.
 */
class EmployerPenaltyController extends Controller
{
    /**
     * @inheritdoc
     */
	 
	 public $layout="main_private";
	 
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all EmployerPenalty models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new EmployerPenaltySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
	
	public function actionPenalityView()
    {
	    $this->layout="default_main";
        $searchModel = new EmployerPenaltySearch();
        $employerModel = new EmployerSearch();
        //$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $loggedin = Yii::$app->user->identity->user_id;
        $employer2 = $employerModel->getEmployer($loggedin);
        $employerID = $employer2->employer_id;
        $dataProvider = $searchModel->searchEmployerPenalty(Yii::$app->request->queryParams,$employerID);

        return $this->render('penalityView', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single EmployerPenalty model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new EmployerPenalty model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new EmployerPenalty();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->employer_penalty_id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing EmployerPenalty model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->employer_penalty_id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing EmployerPenalty model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the EmployerPenalty model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return EmployerPenalty the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = EmployerPenalty::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

frontend/modules/repayment/views/employer-penalty/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\modules\repayment\models\EmployerPenalty */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employer-penalty-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'employer_id')->textInput() ?>

    <?= $form->field($model, 'amount')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'penalty_date')->textInput() ?>

    <?= $form->field($model, 'created_at')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/modules/repayment/views/employer-penalty/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\modules\repayment\models\EmployerPenaltySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="employer-penalty-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'employer_penalty_id') ?>

    <?= $form->field($model, 'employer_id') ?>

    <?= $form->field($model, 'amount') ?>

    <?= $form->field($model, 'penalty_date') ?>

    <?= $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/modules/repayment/views/employer-penalty/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\modules\repayment\models\EmployerPenalty */

$this->title = 'Create Employer Penalty';
$this->params['breadcrumbs'][] = ['label' => 'Employer Penalties', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employer-penalty-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/modules/repayment/views/employer-penalty/index.php
<?php

use yii\helpers\Html;
use kartik\tabs\TabsX;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel frontend\modules\repayment\models\EmployerPenaltySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Monthly Penalty';
$this->params['breadcrumbs'][] = $this->title;
?>
	<div class="employer-penalty-index">

<div class="panel panel-info">
                        <div class="panel-heading">
                      <?= Html::encode($this->title) ?>
                        </div>
                        <div class="panel-body">
						
						<?= $this->render('_form', [
                                'model' => $model,
                                ]) ?>

            <?php
            echo TabsX::widget([
                'items' => [

                    [
                        'label' => 'Penalties',
                        'content' => '<iframe src="' . yii\helpers\Url::to(['employer-penalty/penality-view']) . '" width="100%" height="600px" style="border: 0"></iframe>',
                        'id' => '2',
                    ],
					[
                        'label' => 'Penalties Payments',
                        'content' => '<iframe src="' . yii\helpers\Url::to(['employer-penalty-payment/index']) . '" width="100%" height="600px" style="border: 0"></iframe>',
                        'id' => '2',
                    ],
                ],
                'position' => TabsX::POS_ABOVE,
                'bordered' => true,
                'encodeLabels' => false
            ]);
            ?>			
</div>
       </div>
</div>

frontend/modules/repayment/views/employer-penalty/penalityView.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel frontend\modules\repayment\models\EmployerPenaltySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Monthly Penalties';
$this->params['breadcrumbs'][] = $this->title;
?>
	<div class="employer-penalty-index">

<div class="panel panel-info">
                        <div class="panel-heading">
                      <?= Html::encode($this->title) ?>
                        </div>
                        <div class="panel-body">

            <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            //'employer_penalty_id',
            //'employer_id',
            //'amount',
			'penalty_date',
			'created_at',
			[
            'attribute'=>'amount',
            'format'=>'raw',    
            'value' =>function($model)
            {
                 return $model->amount;
            }, 
            'format'=>['decimal',2],
			'hAlign' => 'right',
            ],
            
            //'created_at',

            //['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>		
</div>
       </div>
</div>

frontend/modules/repayment/views/employer-penalty/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\modules\repayment\models\EmployerPenalty */

$this->title = 'Update Employer Penalty: ' . $model->employer_penalty_id;
$this->params['breadcrumbs'][] = ['label' => 'Employer Penalties', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->employer_penalty_id, 'url' => ['view', 'id' => $model->employer_penalty_id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="employer-penalty-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/modules/repayment/views/employer-penalty/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\modules\repayment\models\EmployerPenalty */

$this->title = $model->employer_penalty_id;
$this->params['breadcrumbs'][] = ['label' => 'Employer Penalties', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="employer-penalty-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->employer_penalty_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->employer_penalty_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'employer_penalty_id',
            'employer_id',
            'amount',
            'penalty_date',
            'created_at',
        ],
    ]) ?>

</div>